### PR TITLE
fixes grails/grails-wrapper#5

### PR DESCRIPTION
**Pull request by cosenmarco**
This changes trigger the CLI succesfully but grails-shell is also failing because of the repository change.

### CODE REVIEW

**Comment by jameskleeh** [comment]
We're not currently open to changing the URL. Waiting on a response from JFrog to see the options

**Comment by cosenmarco** [comment]
You realize that the wrapper is currently unusable ? In our case our pipeline is not working. This one, even with the old URL, will give the ability to override through properties...

**Comment by jameskleeh** [comment]
> You realize that the wrapper is currently unusable 

Yes

**Comment by puneetbehl** [comment]
@cosenmarco Thank you, I cherry-picked some of the changes from this PR in #8

**Comment by cosenmarco** [comment]
> @cosenmarco Thank you, I cherry-picked some of the changes from this PR in #8

You're welcome. Glad to help.

**Pull request closed without merging**
